version: '3'

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2

  app1:
    image: tu_imagen_app1
    container_name: app1
    build:
      context: ./app1
    ports:
      - "8000:8000"

  app2:
    image: tu_imagen_app2
    container_name: app2
    build:
      context: ./app2
    ports:
      - "8001:8001"
