services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html

    depends_on:
      - app1
      - app2

  app1:
    build: ./app1
    ports:
      - "8000:8000"

  app2:
    build: ./app2
    ports:
      - "8001:8001"
